on:
  # TODO: change to trigger only when pushes/pr
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
#   build-assets:
#     name: build assets
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - uses: actions/checkout@v1
#       - name: npm build
#         run: |
#           npm install
#           npm run prod
#       - name: save as artifact
#         uses: actions/upload-artifact@v1
#         with:
#           name: assets
#           path: public
#           retention-days: 3

  deploy-production:
    name: deploy
    runs-on: ubuntu-latest
#     needs: [ build-assets ]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
#       - name: fetch assets artifacts
#         uses: actions/download-artifact@v1
#         with:
#           name: assets
#           path: public
      - name: setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.1'
          extension-csv: mbstring, bcmath
      - name: composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: setup deployer
        uses: atymic/deployer-php-action@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: deploy to production
        env:
          DOT_ENV: ${{ secrets.DOT_ENV_PRODUCTION }}
        run: php vendor/bin/dep deploy prod --branch="main" -vv
